name: Train Model on Push

on:
  push:
    paths:
      - 'workflow-CI/**'
  workflow_dispatch:



jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install MLflow
      run: pip install mlflow scikit-learn pandas

    - name: Run MLflow Project
      run: mlflow run ./MLProject
