name: CI - Train and Build Docker for Sleep Disorder Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Jalankan training dengan modelling.py
        run: |
          python MLProject/modelling.py \
            --input MLProject/Sleep_health_and_lifestyle_dataset_preprocessed.csv \
            --output artifacts/sleep-disorder-model

      - name: Build Docker image dari model MLflow
        run: |
          mlflow models build-docker -m artifacts/sleep-disorder-model -n sleep-disorder-model

      - name: Login ke Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Tag dan push Docker image
        run: |
          docker tag sleep-disorder-model ${{ secrets.DOCKER_HUB_USERNAME }}/sleep-disorder-model:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sleep-disorder-model:latest 
