name: CI - MLflow Project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Run training
        run: |
          python MLProject/modelling.py \
            --input MLProject/Sleep_health_and_lifestyle_dataset_preprocessed.csv \
            --output artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sleep-disorder-model
          path: artifacts/
