name: CI - Train and Build Docker for Sleep Disorder Model

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'mlruns/**'
      - '.gitattributes'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          lfs: true

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Jalankan training dengan modelling.py
        run: |
          python MLProject/modelling.py \
            --input MLProject/Sleep_health_and_lifestyle_dataset_preprocessed.csv \
            --output artifacts/sleep-disorder-model

      - name: Cek isi artifacts
        run: ls -lR artifacts/sleep-disorder-model

      - name: Push MLflow log ke GitHub
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes mlruns/
          git commit -m "Track & push MLflow logs" || true
          git push origin main

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image dari model
        run: |
          mlflow models build-docker -m artifacts/sleep-disorder-model/mlflow_model -n sleep-disorder-model

      - name: Tag & Push image ke Docker Hub
        run: |
          docker tag sleep-disorder-model ${{ secrets.DOCKERHUB_USERNAME }}/msml-ardhi:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/msml-ardhi:latest
