name: CI - Train and Build Docker for Sleep Disorder Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Jalankan training dengan modelling.py
        run: |
          python MLProject/modelling.py \
            --input MLProject/Sleep_health_and_lifestyle_dataset_preprocessed.csv \
            --output artifacts/sleep-disorder-model

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image dari model
        run: |
          mlflow models build-docker -m artifacts/sleep-disorder-model -n sleep-disorder-model

      - name: Tag dan Push image ke Docker Hub
        run: |
          docker tag sleep-disorder-model ${{ secrets.DOCKERHUB_USERNAME }}/msml-ardhi:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/msml-ardhi:latest
