name: CI - Train and Build Docker for Sleep Disorder Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r MLProject/requirements.txt

      - name: Jalankan training dengan modelling.py
        run: |
          source venv/bin/activate
          python MLProject/modelling.py \
            --input MLProject/Sleep_health_and_lifestyle_dataset_preprocessed.csv \
            --output artifacts/sleep-disorder-model

      - name: Periksa isi direktori artifacts
        run: |
          ls -lR artifacts/sleep-disorder-model

      - name: Periksa status Docker
        run: |
          docker info

      - name: Cetak variabel lingkungan Docker
        run: |
          env | grep DOCKER

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image dari model
        env:
          DOCKER_HOST: tcp://localhost:2375
        run: |
          source venv/bin/activate
          mlflow models build-docker -m artifacts/sleep-disorder-model/mlflow_model -n sleep-disorder-model

      - name: Tag dan Push image ke Docker Hub
        run: |
          docker tag sleep-disorder-model ${{ secrets.DOCKERHUB_USERNAME }}/msml-ardhi:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/msml-ardhi:latest
