name: Run Preprocessing

on:
  push:
    paths:
      - 'preprocessing/**'
      - 'namadataset_raw/**'
      - '.github/workflows/**'

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Ardhi.py

    - name: Commit processed data
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add preprocessing/namadataset_preprocessing/*.csv
        git commit -m "Auto: Update preprocessed dataset"
        git push
      continue-on-error: true
